### ISSUE TITLE
Cannot initialize Binder. Expected partition was 1 but 0 has been found instead

### ISSUE THREAD

**Issue by michaelmok2021** [schacko-samples/kafka-summit-2021-scst-kstream#2]
I get this error intermittently when I am in development (ie restart springboot app often). Restarting often makes it go away. We are running springboot with spring cloud stream and using Confluent cloud for Kafka hosting.

my pom.xml is 

```properties
        <spring-boot.version>2.4.6</spring-boot.version>
        <spring-cloud-gcp.version>2.0.0</spring-cloud-gcp.version>
        <spring-cloud.version>2020.0.3</spring-cloud.version>

```

My cloud stream yml config file is

```yaml
spring:
  kafka:
    properties:
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='demo'   password='demo';
      bootstrap.servers: sandbox.ap.aws.confluent.cloud:9096
      security.protocol: SASL_SSL
      # client.dns.lookup: use_all_dns_ips
      # Set to 10 seconds, so brokers are not overwhelmed in cases of incorrectly configured or expired credentials
      reconnect.backoff.max.ms: 10000
      # Keep this default for cloud environments
      # request.timeout.ms: 30000
      # client.id: ${siteName}-bv-app
      application.id: ${siteName}-group
      # Best practice for Kafka producer to prevent data loss
    acks: all

```

Error log

```shell
07-10-2021 08:27:00.216 [task-scheduler-4] INFO  o.a.kafka.common.utils.AppInfoParser.<init> - Kafka startTimeMs: 1633566420215 - tx.userId= tx.siteName=
07-10-2021 08:27:01.090 [task-scheduler-4] ERROR o.s.c.s.b.k.p.KafkaTopicProvisioner.getPartitionsForTopic - Cannot initialize Binder - tx.userId= tx.siteName=
java.lang.IllegalStateException: The number of expected partitions was: 1, but 0 has been found instead
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.lambda$getPartitionsForTopic$6(KafkaTopicProvisioner.java:579)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:530)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:394)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:158)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:226)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:91)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:152)
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleProducerBinding$4(BindingService.java:343)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by sobychacko** [comment]
Could you give a reproducible sample or a way to reproduce the issue?

**Comment by michaelmok2021** [comment]
@sobychacko I have created a demo project [fastlane parker](https://github.com/fastlanesoftware/parker.git) which I sent an invite to you. This project need sets that Kafka server to Confluent Kafka cloud. I will try to see if the error persist if it access a local Docker Kafka server. Thanks.

**Comment by michaelmok2021** [comment]
@sobychacko I managed to reproduce the continuous reconnection issue with the [fastlane parker](https://github.com/fastlanesoftware/parker.git) project. To reproduce the issue, you will to connect to a valid Confluent Kafka server and then try to restart the application (within your IDE) multiple times. I can reproduce this within my Intellij IDE. See below the issue.

```shell
2021-10-08 09:29:24.414  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] Adding newly assigned partitions: 
2021-10-08 09:29:24.414  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1] State transition from RUNNING to PARTITIONS_ASSIGNED
2021-10-08 09:29:24.414  INFO 31777 --- [-StreamThread-1] org.apache.kafka.streams.KafkaStreams    : stream-client [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e] State transition from RUNNING to REBALANCING
2021-10-08 09:29:24.454  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1] Restoration took 40 ms for all tasks []
2021-10-08 09:29:24.454  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1] State transition from PARTITIONS_ASSIGNED to RUNNING
2021-10-08 09:29:24.454  INFO 31777 --- [-StreamThread-1] org.apache.kafka.streams.KafkaStreams    : stream-client [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e] State transition from REBALANCING to RUNNING
2021-10-08 09:29:27.327  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] Attempt to heartbeat failed since group is rebalancing
2021-10-08 09:29:27.327  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] (Re-)joining group
2021-10-08 09:29:27.380  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer, groupId=demo-group] Successfully joined group with generation Generation{generationId=35, memberId='demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer-1af875da-31ad-44f2-93e8-d3a8855e48fb', protocol='stream'}
2021-10-08 09:29:27.380  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] Successfully joined group with generation Generation{generationId=35, memberId='demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer-b2f4f491-7969-4f25-a042-22350e29113b', protocol='stream'}
2021-10-08 09:29:27.435  INFO 31777 --- [-StreamThread-1] a.k.s.p.i.a.HighAvailabilityTaskAssignor : Decided on assignment: {cd0e7a12-f186-4683-a37f-94f5199d7a3a=[activeTasks: ([0_0]) standbyTasks: ([]) prevActiveTasks: ([]) prevStandbyTasks: ([]) changelogOffsetTotalsByTask: ([]) taskLagTotals: ([]) capacity: 1 assigned: 1], 4e16fba1-f943-4c9b-a708-1b9265c2a79e=[activeTasks: ([]) standbyTasks: ([]) prevActiveTasks: ([]) prevStandbyTasks: ([]) changelogOffsetTotalsByTask: ([]) taskLagTotals: ([]) capacity: 1 assigned: 0]} with no followup probing rebalance.
2021-10-08 09:29:27.435  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.i.StreamsPartitionAssignor     : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer] Assigned tasks [0_0] including stateful [] to clients as: 
cd0e7a12-f186-4683-a37f-94f5199d7a3a=[activeTasks: ([0_0]) standbyTasks: ([])]
4e16fba1-f943-4c9b-a708-1b9265c2a79e=[activeTasks: ([]) standbyTasks: ([])].
2021-10-08 09:29:27.436  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.i.StreamsPartitionAssignor     : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer] Client cd0e7a12-f186-4683-a37f-94f5199d7a3a per-consumer assignment:
	prev owned active {}
	prev owned standby {demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer-1af875da-31ad-44f2-93e8-d3a8855e48fb=[]}
	assigned active {demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer-1af875da-31ad-44f2-93e8-d3a8855e48fb=[0_0]}
	revoking active {}	assigned standby {}

2021-10-08 09:29:27.436  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.i.StreamsPartitionAssignor     : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer] Client 4e16fba1-f943-4c9b-a708-1b9265c2a79e per-consumer assignment:
	prev owned active {}
	prev owned standby {demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer-b2f4f491-7969-4f25-a042-22350e29113b=[]}
	assigned active {}
	revoking active {}	assigned standby {}

2021-10-08 09:29:27.436  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.i.StreamsPartitionAssignor     : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer] Finished stable assignment of tasks, no followup rebalances required.
2021-10-08 09:29:27.436  WARN 31777 --- [-StreamThread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] The following subscribed topics are not assigned to any members: [demo-completed] 
2021-10-08 09:29:27.436  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] Finished assignment for group at generation 35: {demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer-b2f4f491-7969-4f25-a042-22350e29113b=Assignment(partitions=[], userDataSize=40), demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer-1af875da-31ad-44f2-93e8-d3a8855e48fb=Assignment(partitions=[demo-received-0], userDataSize=48)}
2021-10-08 09:29:27.490  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] Successfully synced group in generation Generation{generationId=35, memberId='demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer-b2f4f491-7969-4f25-a042-22350e29113b', protocol='stream'}
2021-10-08 09:29:27.490  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer, groupId=demo-group] Successfully synced group in generation Generation{generationId=35, memberId='demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer-1af875da-31ad-44f2-93e8-d3a8855e48fb', protocol='stream'}
2021-10-08 09:29:27.491  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.SubscriptionState    : [Consumer clientId=demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer, groupId=demo-group] Assigned partition demo-received-0 for non-subscribed topic; subscription is [demo-completed]
2021-10-08 09:29:27.491  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] Updating assignment with
	Assigned partitions:                       []
	Current owned partitions:                  []
	Added partitions (assigned - owned):       []
	Revoked partitions (owned - assigned):     []

2021-10-08 09:29:27.491  WARN 31777 --- [-StreamThread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer, groupId=demo-group] We received an assignment [demo-received-0] that doesn't match our current subscription Subscribe(demo-completed); it is likely that the subscription has changed since we joined the group. Will try re-join the group with current subscription
2021-10-08 09:29:27.491  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=demo-group-cd0e7a12-f186-4683-a37f-94f5199d7a3a-StreamThread-1-consumer, groupId=demo-group] (Re-)joining group
2021-10-08 09:29:27.491  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] Notifying assignor about the new Assignment(partitions=[], userDataSize=40)
2021-10-08 09:29:27.492  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.i.StreamsPartitionAssignor     : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer] No followup rebalance was requested, resetting the rebalance schedule.
2021-10-08 09:29:27.492  INFO 31777 --- [-StreamThread-1] o.a.k.s.processor.internals.TaskManager  : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1] Handle new assignment with:
	New active tasks: []
	New standby tasks: []
	Existing active tasks: []
	Existing standby tasks: []
2021-10-08 09:29:27.492  INFO 31777 --- [-StreamThread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1-consumer, groupId=demo-group] Adding newly assigned partitions: 
2021-10-08 09:29:27.492  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1] State transition from RUNNING to PARTITIONS_ASSIGNED
2021-10-08 09:29:27.493  INFO 31777 --- [-StreamThread-1] org.apache.kafka.streams.KafkaStreams    : stream-client [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e] State transition from RUNNING to REBALANCING
2021-10-08 09:29:27.575  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1] Restoration took 82 ms for all tasks []
2021-10-08 09:29:27.576  INFO 31777 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [demo-group-4e16fba1-f943-4c9b-a708-1b9265c2a79e-StreamThread-1] State transition from PARTITIONS_ASSIGNED to RUNNING
```
